### ISSUE TITLE
nginx

### ISSUE THREAD

**Issue by sanchezzzhak** [samdark/wnmp-dev#2]
Под nginx в винде не обязательно указывать полный путь от диска в конфигах
можно указывать относительный от nginx.exe и будет работать.
root host/site1/public_html

Можно добавить 
редиску и монгу.
Подчеркну также пути в конфигах не полные делать.

Можно добавить еще sphinx 2.2.5b но тут только полный путь в конфигах придется делать.
Тестировал эту версию отлично работает как под вендой так и под линям, много багов исправили и недочетов.

**Comment by samdark** [comment]
Конфиг для примера. Остальное опционально.
